"use client";

import React from "react";
import Link from "next/link";
import { useLandingLanguage } from "./LandingLanguageContext";

export function Footer() {
  const { lang, setLang, t } = useLandingLanguage();
  const sections = [[t.footer.columns.product.title, t.footer.columns.product.links, "#diferenciadores"], [t.footer.columns.industries.title, t.footer.columns.industries.links, "#como-funciona"], [t.footer.columns.company.title, t.footer.columns.company.links, "#contacto"]] as const;
  return <footer id="contacto" className="bg-ink text-paper"><div className="border-t border-dashed border-paper/35"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-12 sm:px-6 md:grid-cols-[1.3fr_repeat(4,1fr)] lg:px-8"><div><Link href="/" className="inline-flex items-center gap-1 font-bricolage text-3xl font-bold tracking-tight"><span className="grid size-8 place-items-center bg-grape text-paper [clip-path:polygon(0_0,100%_0,100%_72%,72%_100%,0_100%)]">A</span>gendur</Link><p className="mt-4 max-w-sm text-sm leading-relaxed text-paper/60">{t.footer.tagline}</p><div className="mt-6 inline-flex border border-paper/40" aria-label={t.footer.langLabel}>{(["es", "en"] as const).map((option) => <button key={option} type="button" onClick={() => setLang(option)} aria-pressed={lang === option} className={`px-3 py-2 text-xs font-bold ${lang === option ? "bg-paper text-ink" : "text-paper hover:text-flame"}`}>{option.toUpperCase()}</button>)}</div></div>{sections.map(([heading, links, href]) => <div key={heading}><h3 className="font-bricolage text-lg font-semibold">{heading}</h3><ul className="mt-4 space-y-3 text-sm text-paper/60">{links.map((link) => <li key={link}><a href={href} className="hover:text-flame">{link}</a></li>)}</ul></div>)}<div><h3 className="font-bricolage text-lg font-semibold">{t.footer.columns.legal.title}</h3><ul className="mt-4 space-y-3 text-sm text-paper/60"><li><Link href="/privacidad" className="hover:text-flame">{t.footer.columns.legal.links[0]}</Link></li><li><Link href="/terminos" className="hover:text-flame">{t.footer.columns.legal.links[1]}</Link></li><li><span>{t.footer.columns.legal.links[2]}</span></li></ul></div></div></div><div className="border-t border-paper/15 py-5 text-center text-xs text-paper/45">{t.footer.copyright}</div></footer>;
}
